Update text embedding component (#532)
PR that modifies the text embedding component: 
* Change the name of the component to `embed_text` for consistency (we
already have an `embed_image` component)
* Added VertexAI as a possible model to use 
* Changed the base image to pytorch since some of the dependencies in
the requirement have cuda deps
* Fixed some tests (mainly path related)

Tested the component with the CC rag pipeline and works fine (added the
[`op`](https://github.com/ml6team/fondant/pull/528/commits/fcf86640db82310cc05ffbaddce07bbb8915608b)
here).

The component runs fine (exit code 0) however there seems to be an error
that pops since the connection with the API does not seem to shutdown
gracefully.

```
rag-cc-pipeline-embed_text-1     | [2023-10-18 13:58:45,227 | root | INFO] Writing data...
[########################################] | 100% Completed | 52.61 ss
rag-cc-pipeline-embed_text-1     | [2023-10-18 13:59:37,967 | fondant.executor | INFO] Saving output manifest to gs://soy-audio-379412_kfp-artifacts/custom_artifact/rag-cc-pipeline/rag-cc-pipeline-20231018155832/embed_text/manifest.json
rag-cc-pipeline-embed_text-1     | [2023-10-18 13:59:37,967 | fondant.executor | INFO] Writing cache key to gs://soy-audio-379412_kfp-artifacts/custom_artifact/rag-cc-pipeline/cache/dd3a24cb288cd0eaba12063d2885bc9d.txt
rag-cc-pipeline-embed_text-1     | Traceback (most recent call last):
rag-cc-pipeline-embed_text-1     |   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 110, in grpc._cython.cygrpc.shutdown_grpc_aio
rag-cc-pipeline-embed_text-1     |   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 114, in grpc._cython.cygrpc.shutdown_grpc_aio
rag-cc-pipeline-embed_text-1     |   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 78, in grpc._cython.cygrpc._actual_aio_shutdown
rag-cc-pipeline-embed_text-1     | AttributeError: 'NoneType' object has no attribute 'POLLER'
rag-cc-pipeline-embed_text-1     | Exception ignored in: 'grpc._cython.cygrpc.AioChannel.__dealloc__'
rag-cc-pipeline-embed_text-1     | Traceback (most recent call last):
rag-cc-pipeline-embed_text-1     |   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 110, in grpc._cython.cygrpc.shutdown_grpc_aio
rag-cc-pipeline-embed_text-1     |   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 114, in grpc._cython.cygrpc.shutdown_grpc_aio
rag-cc-pipeline-embed_text-1     |   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 78, in grpc._cython.cygrpc._actual_aio_shutdown
rag-cc-pipeline-embed_text-1     | AttributeError: 'NoneType' object has no attribute 'POLLER'
```

Normally this would be done with a client but in this case we're
initializing the model directly